version: '3.9'

# Network
networks:
  web_network:
    name: svelte_layout_network
    driver: bridge

# Services
services:

  # vue App Development
  svelte_dev:
    build: 
      context: ./svelte-frontend
      dockerfile: Dockerfile.dev
    container_name: svelte_dev
    restart: always
    volumes:
      - ./svelte-example:/usr/app
      - /usr/app/node_modules  # Bookmarks Volume
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
  # vue App Development
  vue_dev:
    build: 
      context: ./vue-frontend
      dockerfile: Dockerfile.dev
    container_name: vue_dev
    restart: always
    volumes:
      - ./vue-frontend:/usr/app
      - /usr/app/node_modules  # Bookmarks Volume
    ports:
      - 5176:5176
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
  react_dev:
    build: 
      context: ./react-frontend
      dockerfile: Dockerfile.dev
    container_name: react_dev
    restart: always
    volumes:
      - ./react-frontend:/usr/app
      - /usr/app/node_modules  # Bookmarks Volume
    ports:
      - 5175:5175
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
  # React App Production
  # reactapp_prod:
  #   build: 
  #     context: ./app
  #     dockerfile: Dockerfile.prod
  #   container_name: reactapp_prod
  #   restart: always
  #   ports:
  #     - 4173:4173
  #   networks:
  #     - web_network

  # Nginx Web Server
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_reactapp
  #   restart: always
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - reactapp_prod
  #   networks:
  #     - web_network
