# Pull the base image
FROM node:20-alpine3.19

# Set the working directory
WORKDIR /usr/app

# Copy app dependencies to container
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy code from host to container
COPY . .

# Expose Port
EXPOSE 5175

# Deploy app for local development
CMD [ "npm","run","dev" ]